name: samdul
services:
  blog:
    build: ./docker/httpd
    expose:
      - 80 
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
  load_balancer:
    # build: ./docker/nginx
    image: nginxproxy/nginx-proxy:1.6
    container_name: blog-lb
    ports:
      - 81:80
    depends_on:
      - blog
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
